apiVersion: apps/v1
kind: Deployment #type of object
metadata:
  name: comments-depl #when pod is created, give it a name
spec:
  replicas: 1 #number of pods we want to create
  selector:
    matchLabels:
      app: comments # tell deployment to find a pod with a label of app: comments
  template: # configuration that is going to apply the pod
    metadata:
      labels: # we want the pod to have a label of app: comments
        app: comments
    spec:
      containers:
        - name: comments #name for the container inside the pod
          image: tlhsieh0610/comments #default latest

---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
