apiVersion: apps/v1
kind: Deployment #type of object
metadata:
  name: event-bus-depl #when pod is created, give it a name
spec:
  replicas: 1 #number of pods we want to create
  selector:
    matchLabels:
      app: event-bus # tell deployment to find a pod with a label of app: event-bus
  template: # configuration that is going to apply the pod
    metadata:
      labels: # we want the pod to have a label of app: event-bus
        app: event-bus
    spec:
      containers:
        - name: event-bus #name for the container inside the pod
          image: tlhsieh0610/event-bus #default latest

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
