apiVersion: apps/v1
kind: Deployment #type of object
metadata:
  name: moderation-depl #when pod is created, give it a name
spec:
  replicas: 1 #number of pods we want to create
  selector:
    matchLabels:
      app: moderation # tell deployment to find a pod with a label of app: moderation
  template: # configuration that is going to apply the pod
    metadata:
      labels: # we want the pod to have a label of app: moderation
        app: moderation
    spec:
      containers:
        - name: moderation #name for the container inside the pod
          image: tlhsieh0610/moderation #default latest

---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
