apiVersion: apps/v1
kind: Deployment #type of object
metadata:
  name: query-depl #when pod is created, give it a name
spec:
  replicas: 1 #number of pods we want to create
  selector:
    matchLabels:
      app: query # tell deployment to find a pod with a label of app: query
  template: # configuration that is going to apply the pod
    metadata:
      labels: # we want the pod to have a label of app: query
        app: query
    spec:
      containers:
        - name: query #name for the container inside the pod
          image: tlhsieh0610/query #default latest

---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
